In [1]:
import numpy as np

In [2]:
#creating a numpy list
mylist = [i for i in range(10)] #this is a list
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# you cant easily multiply every member of a list i.e if you multiply it just makes
mylist * 2


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
# you have to change it to a numpy array
myarray = np.array(mylist)
type(myarray)

numpy.ndarray

In [5]:
myarray*2 # you can multiply every member of the array using this method.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# creating a numpy matrix you can do that by using np.array([[what you want on the first row],[what you want in the second row]...])
mymatrix = np.array([[0,1,5],[-2,1,4],[7,8,9]])
mymatrix

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

In [11]:
# You can collect a specific row from the matrix using matrixname[Starting index of row: ending index of row,index of colum:index of ending row(not included)]
#"putting a ":" means all items"
mymatrix[:,0:1]

array([[ 0],
       [-2],
       [ 7]])

In [12]:
mymatrix[:,1:2]

array([[1],
       [1],
       [8]])

In [13]:
mymatrix[0:2,2:3]

array([[5],
       [4]])

In [14]:
mymatrix[:,:]

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

## arange

Returns evenly spaced values in a given interval

In [15]:
myarange = np.arange(10)
myarange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#.arange(starting num,ending num, how much you want to increment by)
myrangestep = np.arange(0,10,2)
myrangestep

array([0, 2, 4, 6, 8])

In [17]:
#Generate a 3 by 3 matrix of zeroes to balance datasets make sure you put them in double paranthesis
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#generate an array of zeroes
Z = np.zeros(4)
Z

array([0., 0., 0., 0.])

In [21]:
O1 = np.ones(5)
O1

array([1., 1., 1., 1., 1.])

In [23]:
#make sure you put in them in double parenthesis
O6 = np.ones((6,6))
O6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
#linspace returns evenly spaced numbers over a specified interval

In [29]:
#.linspace(starring number, ending number, how many numbers you want)
# The numbers it returns are all evenly spaced on an interval of 25
L = np.linspace(0,25,9)
L

array([ 0.   ,  3.125,  6.25 ,  9.375, 12.5  , 15.625, 18.75 , 21.875,
       25.   ])

In [30]:
R = np.linspace(0,25,36)
R

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ,
       10.71428571, 11.42857143, 12.14285714, 12.85714286, 13.57142857,
       14.28571429, 15.        , 15.71428571, 16.42857143, 17.14285714,
       17.85714286, 18.57142857, 19.28571429, 20.        , 20.71428571,
       21.42857143, 22.14285714, 22.85714286, 23.57142857, 24.28571429,
       25.        ])

In [32]:
#reshape makes the linspace a matrix, the amount of numbers you want(third argument), must equal the amount of spaces in the matrix
#i.e making a 3 by 3 matrix using a linspace the linapce must have 9 elements.
L3 = L.reshape(3,3)
L3

array([[ 0.   ,  3.125,  6.25 ],
       [ 9.375, 12.5  , 15.625],
       [18.75 , 21.875, 25.   ]])

In [33]:
#eye creates an identity matrix
I2 = np.eye(2)
I2

array([[1., 0.],
       [0., 1.]])

In [35]:
I4 = np.eye(4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#creates a 4 by 3 identity matrix
I43 = np.eye(4,3)
I43

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [39]:
#grabing a colum from the Identity matrix
# same as grabbing items from a matrix
I43[0:2,0:2]

array([[1., 0.],
       [0., 1.]])

In [40]:
import random

In [42]:
#rand creates an array or matrix of a given shape with random samples of a given distribution between [0,1)
arr = np.random.rand(3,4)
arr

array([[0.00351102, 0.11419786, 0.51127875, 0.86126816],
       [0.77189451, 0.10778949, 0.30775553, 0.86118743],
       [0.55020255, 0.68103387, 0.17342623, 0.74383763]])

In [43]:
from numpy.random import rand #simplyfies declararation of rand

In [45]:
arr_simple = rand(3,4)
arr_simple

array([[0.49265832, 0.7911863 , 0.68979333, 0.76518703],
       [0.3397335 , 0.09379725, 0.03260581, 0.43817691],
       [0.8048667 , 0.7568558 , 0.70134458, 0.07639982]])

In [47]:
#randn does the same thing as rand but uses the standard normal distribution.
from numpy.random import randn

In [49]:
mat = randn(3,2)
mat

array([[-1.78715719, -1.35572161],
       [-1.71527438,  0.07302505],
       [-0.33405748, -0.39365262]])

In [50]:
#lambda expressions
seq = [i for i in range(5)]
seq

[0, 1, 2, 3, 4]

In [53]:
l = lambda x: x.split('@')[0] 
l("sucyy@gmail.com")

'sucyy'